source 'https://rubygems.org'


gem 'rspec'
gem 'rest-client'
gem 'rack-test'
gem 'json'
gem 'virtus'
gem 'timezone'
gem 'tzinfo'
gem 'typhoeus'
gem 'pry'
gem 'hashie'
gem 'enum', '~> 1.0'
gem 'hashdiff'
gem 'parallel'
gem 'builder', '3.2.2'
gem 'rspec-legacy_formatters', '1.0.0'
gem 'rspec_junit_formatter', '0.2.3'
gem 'ffi'
gem 'api_authenticator', git: 'https://github.com/Spokeo/api_authenticator'
